### ISSUE TITLE
%url% uses feed URL and not post URL

### ISSUE THREAD

**Issue by ryanlua** [azu/rss-to-twitter#3]
## Describe the bug: バグの概要

When you use the `%url%` placeholder it links to the feed and not the post.

## To Reproduce: 再現手順
1. Use %url% in the `TWEET_TEMPLATE`
2. Instead of using the post URL it will always use the URL for the feed
 
## Expected behavior: 期待する動作

When I want to post a tweet and include a blog's URL, I expect it to have a link to the blog post and not just the blog. 

## Operating environment: バグが発生した環境
 - Version of software
 - OS: [e.g. Windows10]
 - Browser: [e.g. Chrome, Safari]
 - etc.

**Comment by azu** [comment]
Can I get a reproduce feed url?

I'm currently using the URL of the post.

https://github.com/azu/rss-to-twitter/blob/aff320f38e4916c3c9c8f303410b5a6721be97ba/src/process.ts#L111

**Comment by ryanlua** [comment]
Oops, looks like I didn't set up my Zapier RSS feed right to properly link the RSS feed. All good now.
